### ISSUE TITLE
First execution of renew_certificate.sh

### ISSUE THREAD

**Issue by zimtls** [Yannik/qnap-letsencrypt#103]
Hello, 

I just installed the letsecnrypt certificate on my QNAP NAS, i've follow your instructions but i have an error with the script : renew_certificate.sh

My setup is OK, i have python 3.5, my NAS is reachable from the public internet. 

The error : 
```
[/share/CACHEDEV1_DATA/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Sat, 19 Jun 2021 14:16:21 +0200
Renewing certificate...
qnap-letsencrypt version: 21afc01
Using python path: python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 28585
Parsing account key...
Parsing CSR...
Found domains: nas.<Mydomain>
Getting directory...
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/share/CACHEDEV1_DATA/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/share/CACHEDEV1_DATA/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 106, in get_crt
    directory, _, _ = _do_request(directory_url, err_msg="Error getting directory")
  File "/share/CACHEDEV1_DATA/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error getting directory:
Url: https://acme-v02.api.letsencrypt.org/directory
Data: None
Response Code: None
Response: <urlopen error unknown url type: https>
An error occured. Restoring system state.
Start apache proxy: OK
./renew_certificate.sh: line 11: 28585 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/CACHEDEV1_DATA/qnap-letsencrypt/tmp-webroot)
Recover apache confiugre
Starting Qthttpd services: Qthttpd.
```

Any ideas for this problem ? 

Thank's in advanced,

**Comment by aetasoul** [comment]
Hi,
Can you clarify how you installed Python?

**Comment by zimtls** [comment]
Hi,
I install Python 3.5 app, with GUI / app center.

**Comment by aetasoul** [comment]
Try reinstating it

**Comment by zimtls** [comment]
I've reinstating it, but same error 😅

**Comment by aetasoul** [comment]
Try this: https://github.com/Yannik/qnap-letsencrypt/issues/26

**Comment by Yannik** [comment]
You could try finding all python executables on your system with something like this: `find / -type f -name "python*"`, and execute [this test](https://github.com/Yannik/qnap-letsencrypt#how-to-test-whether-a-python-script-fails-due-to-missing-ca-certificates) for each.

**Comment by Yannik** [comment]
@LennyM8472 Please check if https://github.com/Yannik/qnap-letsencrypt/commit/4a85d41096a8198b318b8e2afa062290f9323938 fixed this for you.

**Comment by LennyM8472** [comment]
I get this plus a lot of thing sin Docker containers

/usr/share/Python/bin/python

**Comment by Yannik** [comment]
Try the test (https://github.com/Yannik/qnap-letsencrypt#how-to-test-whether-a-python-script-fails-due-to-missing-ca-certificates) with `/share/CE_CACHEDEV2_DATA/.qpkg/Python3/src/bin/python3`

**Comment by LennyM8472** [comment]
[/share/CE_CACHEDEV2_DATA/.qpkg/Python3/src/bin] # /share/CE_CACHEDEV2_DATA/.qpkg/Python3/src/bin/python3.5
Python 3.5.2 (default, Aug 10 2016, 18:01:45)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen # Python 3
urlopen("https://google.com")
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/CE_CACHEDEV2_DATA/.qpkg/Python3/src/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/share/CE_CACHEDEV2_DATA/.qpkg/Python3/src/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/share/CE_CACHEDEV2_DATA/.qpkg/Python3/src/lib/python3.5/urllib/request.py", line 489, in _open
    'unknown_open', req)
  File "/share/CE_CACHEDEV2_DATA/.qpkg/Python3/src/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/share/CE_CACHEDEV2_DATA/.qpkg/Python3/src/lib/python3.5/urllib/request.py", line 1324, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
>>>

**Comment by LennyM8472** [comment]
https://www.qnapclub.eu/de/qpkg/261

**Comment by LennyM8472** [comment]
https://www.forum-nas.fr/threads/qpython3-3-8-6-python3-tons-of-modules.2421/

**Comment by LennyM8472** [comment]
works

[/share/CE_CACHEDEV2_DATA/.qpkg/QPython3/bin] # /share/CE_CACHEDEV2_DATA/.qpkg/QPython3/bin/python3
Python 3.8.6 (default, Oct 12 2020, 08:31:26)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen # Python 3
>>> urlopen("https://google.com")
<http.client.HTTPResponse object at 0x7fb1ab56b520>
>>>

**Comment by LennyM8472** [comment]
each or together? In Terminal or in python3 of Qpython3?

**Comment by Yannik** [comment]
I have pushed the required changes on branch use-qpython-if-available:
https://github.com/Yannik/qnap-letsencrypt/tree/use-qpython-if-available

Please test the changes

**Comment by LennyM8472** [comment]
thnks, now the question is how to change the branch. I not an expert with git
