### ISSUE TITLE
ValueError: Error getting directory - SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by T-I-K** [Yannik/qnap-letsencrypt#108]
**Platform/Firmware Information**

```
Platform = X86_BAYTRAIL
DISPLAY_NAME = TS-453 Pro

Model = TS-X53
Internal Model = TS-X53
Version = 4.3.6
Build Number = 20190704
Rsync Model = QNAP
Build Date = 2019-07-04
```

**Is this the latest firmware for your device?**
No

**Issue Summary:**
Since October I encountered the following issue:
```
Getting directory...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 199, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 195, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
  File "acme-tiny/acme_tiny.py", line 105, in get_crt
    directory, _, _ = _do_request(directory_url, err_msg="Error getting directory")
  File "acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error getting directory:
Url: https://acme-v02.api.letsencrypt.org/directory
Data: None
Response Code: None
Response: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
```
I think it's related to the change of the Let's Encrypt root certificate.

qnap-letsencrypt is up-to-date
acme-tiny is up-to-date
cacert.pem is up-to-date

Access using curl with the CA bundle is working:
curl -v https://acme-v02.api.letsencrypt.org/directory --cacert letsencrypt/cacert.pem
```
*   Trying 2606:4700:60:0:f53d:5624:85c7:3a2c...
* Connected to acme-v02.api.letsencrypt.org (2606:4700:60:0:f53d:5624:85c7:3a2c) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: letsencrypt/cacert.pem
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*        subject: CN=acme-v02.api.letsencrypt.org
*        start date: 2021-09-30 00:27:02 GMT
*        expire date: 2021-12-29 00:27:01 GMT
*        subjectAltName: acme-v02.api.letsencrypt.org matched
*        issuer: C=US; O=Let's Encrypt; CN=R3
*        SSL certificate verify ok.
> GET /directory HTTP/1.1
> Host: acme-v02.api.letsencrypt.org
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 14 Oct 2021 19:40:16 GMT
< Content-Type: application/json
< Content-Length: 658
< Connection: keep-alive
< Cache-Control: public, max-age=0, no-cache
< X-Frame-Options: DENY
< Strict-Transport-Security: max-age=604800
<
{
  "j_x7syJEGL4": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
* Connection #0 to host acme-v02.api.letsencrypt.org left intact
```

Any ideas what's going wrong?

**Comment by T-I-K** [comment]
I found the issue:
My cacert.pem bundle was located in the letsencrypt subfolder, the wrong location.

But now I run into a different issue:
```
Downloading intermediate certificate...
ERROR: cannot verify letsencrypt.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to letsencrypt.org insecurely, use `--no-check-certificate'.
```
Any ideas to avoid the _--no-check-certificate_ option of _wget_?

**Comment by Yannik** [comment]
@T-I-K Can you please try ` wget --ca-certificate=cacert.pem`

**Comment by T-I-K** [comment]
Hi Yannik,

I already tested this without success:
wget --ca-certificate=cacert.pem --no-verbose --secure-protocol=TLSv1_2 -O - https://letsencrypt.org/certs/lets-encrypt-r3.pem
```
ERROR: cannot verify letsencrypt.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to letsencrypt.org insecurely, use `--no-check-certificate'.
```

Even curl does not work using https://letsencrypt.org/certs/:
curl -v https://letsencrypt.org/certs --cacert cacert.pem
```
*   Trying 2a03:b0c0:3:d0::d23:e001...
* Connected to letsencrypt.org (2a03:b0c0:3:d0::d23:e001) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: cacert.pem
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: certificate has expired
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

While this connection is still working (log see previous message):
curl -v https://acme-v02.api.letsencrypt.org/directory --cacert cacert.pem

The interesting part may be:
curl -v https://letsencrypt.org/certs --insecure
```
*   Trying 2a03:b0c0:3:d0::d26:4001...
* Connected to letsencrypt.org (2a03:b0c0:3:d0::d26:4001) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*        subject: CN=lencr.org
*        start date: 2021-10-10 03:00:44 GMT
*        expire date: 2022-01-08 03:00:43 GMT
*        issuer: C=US; O=Let's Encrypt; CN=R3
*        SSL certificate verify result: certificate has expired (10), continuing anyway.
> GET /certs HTTP/1.1
> Host: letsencrypt.org
> User-Agent: curl/7.43.0
...
```
**expire date: 2022-01-08** 03:00:43 GMT
**SSL certificate** verify result: certificate **has expired** (10), continuing anyway.

In ubuntu1804 with almost up2date certificate store requests using curl to https://letsencrypt.org/certs are working fine.

Because I've only basic knowledge about the SSL certificate things I don't know what's going wrong here.

**Comment by T-I-K** [comment]
date
```
Fri Oct 15 13:18:25 CEST 2021
```

**Comment by Yannik** [comment]
What's the output of `openssl s_client -showcerts -connect letsencrypt.org:443` and `openssl s_client -showcerts -CAfile cacert.pem -connect letsencrypt.org:443`?

**Comment by Yannik** [comment]
What about ` wget --ca-certificate=cacert.pem --ca-directory=/dev/null --no-verbose --secure-protocol=TLSv1_2 -O - https://letsencrypt.org/certs/lets-encrypt-r3.pem`

**Comment by Yannik** [comment]
Does it work without `export SSL_CERT_DIR=/dev/null` or is that required?

**Comment by T-I-K** [comment]
It seems _export SSL_CERT_DIR=/dev/null_ is also a suitable option for _wget_.

The following is working fine now:
```
export SSL_CERT_FILE=cacert.pem
export SSL_CERT_DIR=/dev/null
wget --no-verbose --secure-protocol=TLSv1_2 -O - https://letsencrypt.org/certs/lets-encrypt-r3.pem
```
So you have to add _export SSL_CERT_DIR=/dev/null_ to _renew_certificate.sh_.
I can't test the whole script because I hit the order rate limit.
