### ISSUE TITLE
Unable to renew certificate

### ISSUE THREAD

**Issue by Muyz** [Yannik/qnap-letsencrypt#115]
During a first run, I get errors shown below. 

Checking whether to renew certificate on Wed, 22 Dec 2021 02:16:27 +0100
Renewing certificate...
qnap-letsencrypt version: 452dc7d
Using python path: /opt/QPython39/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 19921
Parsing account key...
Parsing CSR...
Found domains: <domain names/>
Getting directory...
Directory found!
Registering account...
Already registered! Account ID: https://acme-v02.api.letsencrypt.org/acme/acct/........
Creating new order...
Order created!
Verifying <domain/>...
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/homes/admin/qnapletsencrypt/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 145, in get_crt
    assert (disable_check or _do_request(wellknown_url)[0] == keyauthorization)
  File "/share/CACHEDEV1_DATA/homes/admin/qnapletsencrypt/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error:
Url: http://<domain/>/.well-known/acme-challenge/<key/>
Data: None
Response Code: 404
Response: 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Cache-Control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />
<link rel="shortcut icon" href="/images/favicon.gif" type="image/gif" />
<link rel="icon" href="/images/favicon.gif" type="image/gif" />
<style type="text/css">
body{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 11px;
background: #FFFFFF url('/cgi-bin/images/error/err_bg.jpg');

etc. etc.

Had to modify the shell script to use Python 3.9, as suggested by Lufthummel in issue #113. Am running QTS 5.0 on a freshly installed TVS672XT.

**Comment by Muyz** [comment]
Might have found the root cause.
