### ISSUE TITLE
/usr/local/bin/python: No module named SimpleHTTPServer

### ISSUE THREAD

**Issue by Pivert** [Yannik/qnap-letsencrypt#25]
**Platform/Firmware Information**
Platform = ARM_MS
DISPLAY_NAME=TS-231
Model = TS-X31
Internal Model = TS-X31
Version = 4.2.3
Build Number = 20170121
Rsync Model = QNAP
Build Date = 2017-01-21

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**
The main problem seems related to the SimpleHTTPServer module missing:
/usr/local/bin/python: No module named SimpleHTTPServer

How can I install this module on the QNAP?

**Full Trace:**
# ./renew_certificate.sh 
Checking whether to renew certificate on Wed, 08 Feb 2017 12:08:24 +0100
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 15119
/usr/local/bin/python: No module named SimpleHTTPServer
Parsing account key...
Parsing CSR...
Registering account...
Registered!
Verifying nas.heli-luxembourg.com...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/fAPQH94uFFA7bIErDBxERT4DZePfEV9xalQx2tg8EkE, but couldn't download http://nas.heli-luxembourg.com/.well-known/acme-challenge/fAPQH94uFFA7bIErDBxERT4DZePfEV9xalQx2tg8EkE

**Comment by Pivert** [comment]
Problem fixed by installing Python from the Package manager through the web interface.
I was in fact using the default micro python installation that comes installed by default.
