### ISSUE TITLE
Difficulties with renew_certificate.sh

### ISSUE THREAD

**Issue by aski71** [Yannik/qnap-letsencrypt#31]
Hi, I've been following your steps and landed flat on my face with renew_certificate.sh.
I receive the following output:

```
Checking whether to renew certificate on Tue, 23 May 2017 19:10:58 +0200
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 8180
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/SimpleHTTPServer.py", line 230, in <module>
    test()
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/SimpleHTTPServer.py", line 226, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying bigbuddy.myqnapcloud.com...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/zmrXYd5rdzNcfM_IKeJVXr1feib3fgssrWDszYw7MrI, but couldn't download http://bigbuddy.myqnapcloud.com/.well-known/acme-challenge/zmrXYd5rdzNcfM_IKeJVXr1feib3fgssrWDszYw7MrI
```

**Platform/Firmware Information**

```
Platform = X86_PINEVIEW
Model = TS-459
Internal Model = TS-459
Version = 4.2.6
Build Number = 20170517
Rsync Model = QNAP
Build Date = 2017-05-17
```

**Is this the latest firmware for your device?**
yes

**Issue Summary (provide relevant error messages and log output):**

**Comment by Yannik** [comment]
Obviously your server is not reachable from the public internet.

**Comment by aski71** [comment]
You are right. After quite a time of experimenting I found out that UPNP changed the ports due to another QNAP system in my network already claiming port 80. Even though I had deactivated this, it seemed to enable itself again after reboot. So I decided to switch off UPNP entirely and manually open the appropriate ports on my router.

That said I have another suggestion:
Why complicate things setting up a temporary web directory, killing the running web server and starting your own? I changed the script to create the validation file in the official QNAP web server path.

**Comment by Yannik** [comment]
> Why complicate things setting up a temporary web directory, killing the running web server and starting your own? I changed the script to create the validation file in the official QNAP web server path.

This is more portable, because the apache webserver can be modified in various ways by the user.

**Comment by aski71** [comment]
All right. Understood. Seems to work fine for me now. Thanks.
