### ISSUE TITLE
Doesn't support domain with both IPv4 (A) and IPv6 (AAAA) DNS records

### ISSUE THREAD

**Issue by msnelling** [Yannik/qnap-letsencrypt#37]
**Platform/Firmware Information**

```
Platform = X86_PINEVIEW
Model = TS-459
Internal Model = TS-459
Version = 4.2.6
Build Number = 20171208
Rsync Model = QNAP
Build Date = 2017-12-08
```

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**
Script doesn't support domain with both IPv4 (A) and IPv6 (AAAA) DNS records.
```
[/share/MD0_DATA/Apps/qnap-letsencrypt] # ./renew_certificate.sh                  
Checking whether to renew certificate on Sat, 23 Dec 2017 11:58:02 +0000
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 19869
Traceback (most recent call last):
  File "../HTTPServer.py", line 22, in <module>
    main()
  File "../HTTPServer.py", line 11, in main
    servev6()
  File "../HTTPServer.py", line 14, in servev6
    server = HTTPServerV6(('::', 80), SimpleHTTPRequestHandler)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/SocketServer.py", line 417, in __init__
    self.socket_type)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 97] Address family not supported by protocol
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying my.domain.com...
192.168.1.1 - - [23/Dec/2017 11:58:13] "GET /.well-known/acme-challenge/XXXXXXX HTTP/1.1" 200 -
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 149, in get_crt
    domain, challenge_status))
ValueError: nas.bakedbeans.com challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'addressesResolved': [u'xxx.xxx.xxx.xxx', u'xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx'], u'url': u'http://my.domain.com/.well-known/acme-challenge/xxx', u'hostname': u'my.domain.com', u'addressesTried': [], u'addressUsed': u'xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx', u'port': u'80'}], u'keyAuthorization': u'xxx', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/-xxx', u'token': u'xxx, u'error': {u'status': 400, u'type': u'urn:acme:error:connection', u'detail': u'Fetching http://my.domain.com/.well-known/acme-challenge/xxx: Timeout'}, u'type': u'http-01'}
```

**Comment by Yannik** [comment]
What happens if you try this manually:

```
from SimpleHTTPServer import SimpleHTTPRequestHandler
from BaseHTTPServer import HTTPServer
import socket

server_class=HTTPServer
server_class.address_family = socket.AF_INET6
httpd = server_class(('::', 8000), SimpleHTTPRequestHandler)
httpd.handle_request()

```

**Comment by msnelling** [comment]
So if I start python and input the above code I don't get any errors.
```
[/share/MD0_DATA/Apps/qnap-letsencrypt] # python                
Python 2.7.9 (default, Mar 24 2015, 00:42:24) 
[GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from SimpleHTTPServer import SimpleHTTPRequestHandler
from BaseHTTPServer import HTTPServer
import socket

server_class=HTTPServer
server_class.address_family = socket.AF_INET6
httpd = server_class(('::', 8000), SimpleHTTPRequestHandler)
httpd.handle_request()
>>> >>> >>> >>> >>> >>> >>>
```

**Comment by Yannik** [comment]
In this case, I believe something is wrong with your python setup. You should check that.

**Comment by msnelling** [comment]
Hmmm, I’m not sure what to check there. It was installed through the QNAP
App Store.
Any idea what to check, I’m not a python dev?

**Comment by Yannik** [comment]
Try this:
`which -a python | xargs -I {} sh -c 'echo "{} ($(realpath {}), $({} --version 2>&1))"'`

**Comment by msnelling** [comment]
Sadly my QNAP seems to run BusyBox so the `which` and `xargs` command line parameters are invalid but I think this is what you're trying to do...
```
[~] # find / -name python
/mnt/ext/opt/Python/bin/python
/share/MD0_DATA/.qpkg/Python/bin/python
/usr/bin/python
/usr/local/bin/python
[~] # ls -la /usr/local/bin/python
lrwxrwxrwx    1 admin    administ        30 Dec 23 14:06 /usr/local/bin/python -> /mnt/ext/opt/Python/bin/python*
[~] # ls -la /usr/bin/python
lrwxrwxrwx    1 admin    administ        39 Dec 23 14:09 /usr/bin/python -> /share/MD0_DATA/.qpkg/Python/bin/python*
[~] # /mnt/ext/opt/Python/bin/python --version
Python 2.7.5
[~] # /share/MD0_DATA/.qpkg/Python/bin/python --version
```

**Comment by Yannik** [comment]
What is the output of `which python`, though?

You should try the different python installations on your systems by giving a full path here now: https://github.com/Yannik/qnap-letsencrypt/blob/master/renew_certificate.sh#L15

Maybe the error doesn't occur for the non-default installation.

**Comment by msnelling** [comment]
So I removed the Python 2.7.9 .qpkg and am now just running with the standard shipped Python v2.7.5. However now I get the error
```
Checking whether to renew certificate on Mon, 25 Dec 2017 11:39:57 +0000
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 17737
./renew_certificate.sh: line 15: python../HTTPServer.py: No such file or directory
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 2, in <module>
    import argparse, subprocess, json, os, sys, base64, binascii, time, hashlib, re, copy, textwrap, logging
  File "/root/daily_build/4.2.2/Model/TS-459/../../SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/argparse.py", line 85, in <module>
ImportError: No module named collections
```

**Comment by Yannik** [comment]
You definitely need the qpkg. The default python shipped with the nas is a version with only very select features. 
-- 
sent from mobile

**Comment by kasi45** [comment]
hi,
use my script. It is based on the script by Yannik. I use the Qnap webserver as an alternative without any additional software.

The script can be found in the attachment.

[renew_certificate.sh.log](https://github.com/Yannik/qnap-letsencrypt/files/1586084/renew_certificate.sh.log)

**Comment by Yannik** [comment]
@msnelling What is the output of `which python` on your system? Is it not the qpkg-python?

**Comment by Yannik** [comment]
@msnelling Ping ;-)

**Comment by msnelling** [comment]
@Yannik Sorry ,was offline for a few days. Yes `which python` points to the qpkg-python. It must have been a corrupt qpkg installation.

**Comment by Yannik** [comment]
@msnelling So now it works even without hardcoding the python path?

**Comment by msnelling** [comment]
Yes it does.
