### ISSUE TITLE
Issue at running renew_certificate.sh

### ISSUE THREAD

**Issue by catara** [Yannik/qnap-letsencrypt#44]
```
[/share/CACHEDEV4_DATA/HTTPSCERT/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Tue, 27 Mar 2018 21:36:12 +0200
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 11613
Traceback (most recent call last):
  File "../HTTPServer.py", line 26, in <module>
    main()
  File "../HTTPServer.py", line 15, in main
    servev6()
  File "../HTTPServer.py", line 18, in servev6
    server = HTTPServerV6(('::', 80), SimpleHTTPRequestHandler)
  File "/share/CACHEDEV4_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 418, in __init__
    self.server_activate()
  File "/share/CACHEDEV4_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 440, in server_activate
    self.socket.listen(self.request_queue_size)
  File "/share/CACHEDEV4_DATA/.qpkg/Python/src/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/share/CACHEDEV4_DATA/.qpkg/Python/src/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/share/CACHEDEV4_DATA/.qpkg/Python/src/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../HTTPServer.py", line 22, in servev4
    server = HTTPServer(('0.0.0.0', 80), SimpleHTTPRequestHandler)
  File "/share/CACHEDEV4_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 418, in __init__
    self.server_activate()
  File "/share/CACHEDEV4_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 440, in server_activate
    self.socket.listen(self.request_queue_size)
  File "/share/CACHEDEV4_DATA/.qpkg/Python/src/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Parsing account key...
Parsing CSR...
Found domains: capi.ro
Getting directory...
Directory found!
Registering account...
Registered!
Creating new order...
Order created!
Verifying capi.ro...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 197, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 143, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/_w3uZTyKQo-MWHJXFT-RFSPwa2ShESkHKLid55ACa9Y, but couldn't download http://capi.ro/.well-known/acme-challenge/_w3uZTyKQo-MWHJXFT-RFSPwa2ShESkHKLid55ACa9Y: Error:
Url: http://capi.ro/.well-known/acme-challenge/_w3uZTyKQo-MWHJXFT-RFSPwa2ShESkHKLid55ACa9Y
Data: None
Response Code: None
Response: <urlopen error [Errno 111] Connection refused>
```

from what i've seen the webserver start automatically after a stop with /etc/init.d/Qthttpd.sh stop
QNAP Details:
[~] # grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
```
Platform = X86_BAYTRAIL
DISPLAY_NAME = TS-453 Pro
```
[~] # grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["
```
Model = TS-X53
Internal Model = TS-X53
Version = 4.3.4
Build Number = 20180315
Rsync Model = QNAP
Build Date = 2018-03-15
```
[~] # 
Python 2.7.5 (default, Mar 15 2018, 03:06:45)

**help please.**

**Comment by Yannik** [comment]
You are missing the information from the template.

I do not have access to a qnap NAS atm, so you would need to provide further information how to fix this, so I can apply any required changes.

**Comment by catara** [comment]
ts-453pro 8GB RAM
OS 4.3.4.0516
Python 2.7.5 (default, Mar 15 2018, 03:06:45) 

what else(e.g. log,etc.) do you need?

**Comment by Yannik** [comment]
What is the output of
```
grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["
```
Please attach this to the top of your opening post.

As I do not have access to a qnap nas atm, you will need to debug this yourself. I can integrate any required changes upstream.

**Comment by wonderfullyrich** [comment]
I'm getting the same python error using renew_certificate.sh on Python 3.5: 


```
[admin@fox qnap-letsencrypt]$ grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
Platform = X86_APOLLOLAKE
DISPLAY_NAME = TS-453B
[admin@fox qnap-letsencrypt]$ grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["
Model = TS-X53B
Internal Model = TS-X53B
Version = 4.3.4
Build Number = 20180215
Rsync Model = QNAP
Build Date = 2018-02-15
```

It's shutting down qnap httpd services, but I don't have enough experience dealing with python to understand why I'm seeing a threading error with python3 when it initiates services.


```
admin@fox qnap-letsencrypt]$ /share/CACHEDEV1_DATA/letsencrypt/qnap-letsencrypt/renew_certificate.sh
Checking whether to renew certificate on Sun, 08 Apr 2018 17:06:45 -0600
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 2520
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "../HTTPServer.py", line 22, in servev4
    server = HTTPServer(('0.0.0.0', 80), SimpleHTTPRequestHandler)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

Traceback (most recent call last):
  File "../HTTPServer.py", line 26, in <module>
    main()
  File "../HTTPServer.py", line 15, in main
    servev6()
  File "../HTTPServer.py", line 18, in servev6
    server = HTTPServerV6(('::', 80), SimpleHTTPRequestHandler)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/socketserver.py", line 437, in __init__
    self.socket_type)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

**Comment by Yannik** [comment]
does this still happen if you comment out this line? https://github.com/Yannik/qnap-letsencrypt/blob/master/HTTPServer.py#L15

**Comment by Yannik** [comment]
Closing due to inactivity
