### ISSUE TITLE
Issue at renew_certificate.sh

### ISSUE THREAD

**Issue by mendelk** [Yannik/qnap-letsencrypt#51]
**Platform/Firmware Information**

```
Platform = X86_BAYTRAIL
DISPLAY_NAME = TS-251
Model = TS-X51
Internal Model = TS-X51
Version = 4.3.4
Build Number = 20180528
Rsync Model = QNAP
Build Date = 2018-05-28
```

**Is this the latest firmware for your device?**
I believe so

**Issue Summary (provide relevant error messages and log output):**
Running `./renew_certificate.sh` gives the following output:

```
Checking whether to renew certificate on Mon, 09 Jul 2018 20:52:09 -0400
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 22067
Traceback (most recent call last):
  File "../HTTPServer.py", line 36, in <module>
    main()
  File "../HTTPServer.py", line 16, in main
    servev6()
  File "../HTTPServer.py", line 23, in servev6
    server = HTTPServerV6(('::', 80), SimpleHTTPRequestHandler)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../HTTPServer.py", line 32, in servev4
    server = HTTPServer(('0.0.0.0', 80), SimpleHTTPRequestHandler)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Parsing account key...
Parsing CSR...
Found domains: nas.MYDOMAIN.com
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying nas.MYDOMAIN.com...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 144, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/gzeGDxUdzJ_OoTR_6iKSp_YljkqGg-NgDpp8KnVY6No, but couldn't download http://nas.MYDOMAIN.com/.well-known/acme-challenge/gzeGDxUdzJ_OoTR_6iKSp_YljkqGg-NgDpp8KnVY6No: 'ascii' codec can't encode characters in position 2602-2603: ordinal not in range(128)
```

This looks very similar to #44 (and possibly #49), but I intend to follow through with any suggestions! Thank you!

**Comment by mendelk** [comment]
@Yannik Any ideas?

**Comment by powaking** [comment]
Getting similar issue except I'm getting:

Response: <urlopen error [Errno 111] Connection refused>

If I browse to my address on port 80 I see the /.well-known/acme-challenge folder and can browse to it so not sure why I'm getting this error. Also get similar errors as 'mendelk' up until the failure. 

I'm on the latest qnap build as of 7/23/2018 and am trying to renew my cert as the built in function does not appear to be working.

**Comment by Yannik** [comment]
@mendelk Unless you found a solution already, you'll have to find out which service is currently hogging the port ("address already in use"). You can use `lsof -i :80` for example.

**Comment by Yannik** [comment]
close due to inactivity. feel free to reopen if problem persists.

**Comment by odelrio** [comment]
I have the same issue. When running the HTTP server in both IPv4 and IPv6 I get an "address already in use" error.
